import { readFileSync } from 'fs';
import { join } from 'path';
import type { TCGPlayerProductDetails, Edition } from '@/types';

const BASE_URL = 'https://mp-search-api.tcgplayer.com/v1';
const IMAGE_BASE_URL = 'https://product-images.tcgplayer.com/fit-in/437x437';

// Load TCGdex → TCGPlayer set name mapping (generated by discover-tcgplayer-sets.ts)
let tcgplayerSetMap: Record<string, string> = {};
try {
  const mapPath = join(__dirname, 'tcgplayer-set-map.json');
  tcgplayerSetMap = JSON.parse(readFileSync(mapPath, 'utf-8'));
} catch {
  // Map file doesn't exist yet — will be generated by discovery script
}

// Strip common TCGPlayer set name prefixes for better matching
const TCGPLAYER_SET_PREFIXES = /^(SV:\s*|SWSH:\s*|SM:\s*|XY:\s*|BW:\s*|HS:\s*|SV\s+|SWSH\s+|SM\s+|XY\s+|BW\s+|Pokémon\s+TCG\s+)/i;

export function getProductImageUrl(productId: number): string {
  return `${IMAGE_BASE_URL}/${productId}.jpg`;
}

export function getTcgplayerProductUrl(
  productUrlName: string,
  productId: number
): string {
  return `https://www.tcgplayer.com/product/${productId}/pokemon-${productUrlName}`;
}

export async function getProductDetails(
  productId: number
): Promise<TCGPlayerProductDetails | null> {
  try {
    const res = await fetch(`${BASE_URL}/product/${productId}/details`, {
      headers: {
        Accept: 'application/json',
      },
    });

    if (!res.ok) return null;

    const data = await res.json();

    return {
      productId: data.productId,
      productName: data.productName,
      marketPrice: data.marketPrice ?? null,
      lowestPrice: data.lowestPrice ?? null,
      medianPrice: data.medianPrice ?? null,
      lowestPriceWithShipping: data.lowestPriceWithShipping ?? null,
      imageCount: data.imageCount ?? 0,
      setName: data.setName ?? '',
      setUrlName: data.setUrlName ?? '',
      productUrlName: data.productUrlName ?? '',
      productTypeName: data.productTypeName ?? '',
      activeListings: data.activeListings ?? 0,
      sellers: data.sellers ?? 0,
    };
  } catch {
    return null;
  }
}

export async function getProductDetailsBatch(
  productIds: number[],
  concurrency = 5
): Promise<Map<number, TCGPlayerProductDetails>> {
  const results = new Map<number, TCGPlayerProductDetails>();

  // Process in batches to limit concurrency
  for (let i = 0; i < productIds.length; i += concurrency) {
    const batch = productIds.slice(i, i + concurrency);
    const details = await Promise.all(batch.map(getProductDetails));
    for (let j = 0; j < batch.length; j++) {
      if (details[j] != null) {
        results.set(batch[j], details[j]!);
      }
    }
  }

  return results;
}

function getEditionSearchTerms(edition?: Edition | null): string {
  switch (edition) {
    case '1st-edition':
      return ' 1st edition';
    case 'shadowless':
      return ' shadowless';
    case 'unlimited':
      return ' unlimited';
    default:
      return '';
  }
}

function matchesEdition(
  productName: string,
  edition?: Edition | null
): boolean {
  const lower = productName.toLowerCase();
  switch (edition) {
    case '1st-edition':
      return lower.includes('1st edition');
    case 'shadowless':
      return lower.includes('shadowless');
    case 'unlimited':
      return lower.includes('unlimited') || lower.includes('revised');
    default:
      return true;
  }
}

const EXCLUDE_PRODUCT_PATTERNS = [
  /\bbox\b/i,
  /\betb\b/i,
  /\belite\s*trainer/i,
  /\bcase\b/i,
  /\bdisplay\b/i,
  /\bbundle\b/i,
  /\bcollection\b/i,
  /\btin\b/i,
];

function isBoosterPack(productName: string): boolean {
  const lower = productName.toLowerCase();
  if (!lower.includes('booster pack') && !lower.includes('booster')) return false;
  return !EXCLUDE_PRODUCT_PATTERNS.some((p) => p.test(productName));
}

// Accepted product types for booster packs (empty string = unknown, allowed as fallback)
const VALID_PRODUCT_TYPES = ['Booster Pack', 'Sealed Products', ''];

export interface MatchResult {
  product: TCGPlayerSearchResult;
  confidence: number;
  reasons: string[];
}

function scoreMatch(
  result: TCGPlayerSearchResult,
  setName: string,
  edition?: Edition | null
): MatchResult {
  const reasons: string[] = [];
  let score = 0;

  const setLower = setName.toLowerCase();
  const resultSetLower = result.setName.toLowerCase();
  const resultNameLower = result.productName.toLowerCase();

  // Also try matching against TCGPlayer set name with prefix stripped
  const strippedSetLower = resultSetLower.replace(TCGPLAYER_SET_PREFIXES, '').trim();

  // Set name matching (0-0.5)
  if (resultSetLower === setLower || strippedSetLower === setLower) {
    score += 0.5;
    reasons.push('exact set name match');
  } else if (
    resultSetLower.startsWith(setLower + ' ') ||
    resultSetLower.startsWith(setLower + ':') ||
    strippedSetLower.startsWith(setLower + ' ') ||
    strippedSetLower.startsWith(setLower + ':')
  ) {
    score += 0.3;
    reasons.push('set name starts-with match');
  } else if (
    resultSetLower.endsWith(' ' + setLower) ||
    strippedSetLower.endsWith(' ' + setLower)
  ) {
    // Catches "SV: Scarlet & Violet 151" matching "151"
    score += 0.4;
    reasons.push('set name ends-with match');
  } else if (resultSetLower.includes(setLower) || strippedSetLower.includes(setLower)) {
    score += 0.1;
    reasons.push('loose set name match');
  } else {
    reasons.push('no set name match');
  }

  // Product name contains set name (0-0.2)
  if (resultNameLower.includes(setLower)) {
    score += 0.2;
    reasons.push('product name contains set name');
  }

  // Edition match (0-0.2)
  if (matchesEdition(result.productName, edition)) {
    score += 0.2;
    reasons.push('edition match');
  }

  // Has market price (0-0.1)
  if (result.marketPrice != null && result.marketPrice > 0) {
    score += 0.1;
    reasons.push('has market price');
  }

  return { product: result, confidence: Math.min(score, 1), reasons };
}

export interface TCGPlayerSearchResult {
  productId: number;
  productName: string;
  marketPrice: number | null;
  lowestPrice: number | null;
  imageUrl: string;
  setName: string;
  productUrlName: string;
}

export async function searchProducts(
  query: string
): Promise<TCGPlayerSearchResult[]> {
  try {
    const res = await fetch(`${BASE_URL}/search/request?q=${encodeURIComponent(query)}&isList=false`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify({
        algorithm: '',
        from: 0,
        size: 50,
        filters: {
          term: {
            productLineName: ['pokemon'],
          },
          range: {},
          match: {},
        },
        listingSearch: {
          filters: {
            term: {},
            range: {},
            exclude: { channelExclusion: 0 },
          },
          context: { cart: {} },
        },
        context: { cart: {}, shippingCountry: 'US' },
        settings: {},
        sort: {},
        query,
      }),
    });

    if (!res.ok) return [];

    const data = await res.json();
    const results: TCGPlayerSearchResult[] = [];

    const resultSets = data?.results;
    if (!Array.isArray(resultSets)) return [];

    for (const resultSet of resultSets) {
      const aggregations = resultSet?.aggregations;
      if (!aggregations) continue;

      // The search response nests results in aggregations
      const totalResults = resultSet?.totalResults ?? 0;
      if (totalResults === 0) continue;

      // Results are in the main results array
      const items = resultSet?.results;
      if (!Array.isArray(items)) continue;

      for (const item of items) {
        results.push({
          productId: item.productId,
          productName: item.productName ?? '',
          marketPrice: item.marketPrice ?? null,
          lowestPrice: item.lowestPrice ?? null,
          imageUrl: getProductImageUrl(item.productId),
          setName: item.setName ?? '',
          productUrlName: item.productUrlName ?? '',
        });
      }
    }

    return results;
  } catch {
    return [];
  }
}

// Hardcoded product IDs for vintage packs that the search endpoint can't find.
// TCGPlayer's search returns irrelevant modern products for these queries.
// Format: "setName|edition" → productId
const VINTAGE_PACK_IDS: Record<string, number> = {
  // WotC era — Base Set editions
  'Base Set|1st-edition': 138132,  // Base Set (Shadowless) [1st Edition]
  'Base Set|shadowless': 138131,   // Base Set (Shadowless) [Unlimited Edition]
  'Base Set|unlimited': 138130,    // Base Set [Revised Unlimited Edition]
  // WotC era — other sets with editions
  'Jungle|1st-edition': 138128,
  'Jungle|unlimited': 138129,
  'Fossil|1st-edition': 138133,
  'Fossil|unlimited': 138134,
  'Team Rocket|1st-edition': 138136,
  'Team Rocket|unlimited': 138135,
  'Gym Heroes|1st-edition': 138137,
  'Gym Heroes|unlimited': 138138,
  'Gym Challenge|1st-edition': 138140,
  'Gym Challenge|unlimited': 138139,
  'Neo Genesis|1st-edition': 138141,
  'Neo Genesis|unlimited': 138142,
  'Neo Discovery|1st-edition': 138144,
  'Neo Discovery|unlimited': 138143,
  'Neo Revelation|1st-edition': 138145,
  'Neo Revelation|unlimited': 138146,
  'Neo Destiny|1st-edition': 138148,
  'Neo Destiny|unlimited': 138147,
  // WotC era — no editions
  'Base Set 2|': 138149,
  'Legendary Collection|': 138150,
  'Expedition|': 138151,
  'Aquapolis|': 138152,
  'Skyridge|': 138153,
  // ex-era sets (names from TCGdex)
  'Ruby & Sapphire|': 98558,
  'Sandstorm|': 98565,
  'Dragon|': 98519,
  'Team Magma vs Team Aqua|': 98550,
  'Hidden Legends|': 98595,
  'Team Rocket Returns|': 98578,
  'Deoxys|': 98562,
  'Emerald|': 98546,
  'Unseen Forces|': 98577,
  'Legend Maker|': 98557,
  'Holon Phantoms|': 98522,
  'Crystal Guardians|': 98566,
  'Dragon Frontiers|': 98533,
  'Power Keepers|': 98529,
  // DP-era sets
  'Diamond & Pearl|': 98525,
  'Mysterious Treasures|': 98561,
  'Secret Wonders|': 98569,
  'Great Encounters|': 98545,
  'Majestic Dawn|': 98585,
  'Legends Awakened|': 98537,
  'Stormfront|': 98589,
  // Platinum-era sets
  'Platinum|': 98591,
  'Rising Rivals|': 98542,
  'Supreme Victors|': 98574,
  'Arceus|': 98594,
  // HGSS-era sets
  'HeartGold SoulSilver|': 98530,
  'Unleashed|': 98582,
  'Undaunted|': 98586,
  'Triumphant|': 98534,
  'Call of Legends|': 98515,
  // BW-era sets
  'Black & White|': 98553,
  'Emerging Powers|': 98549,
  'Noble Victories|': 98570,
  'Next Destinies|': 98538,
  'Dark Explorers|': 98521,
  'Dragons Exalted|': 98541,
  'Boundaries Crossed|': 98554,
  'Plasma Storm|': 98526,
  'Plasma Freeze|': 98517,
  'Plasma Blast|': 98573,
  'Legendary Treasures|': 98581,
};

export function isVintagePack(setName: string, edition?: Edition | null): boolean {
  const key = `${setName}|${edition ?? ''}`;
  return key in VINTAGE_PACK_IDS;
}

export interface FindPackResult {
  result: TCGPlayerSearchResult;
  confidence: number;
}

// Build a list of search queries to try, from most specific to broadest
function buildSearchQueries(setName: string, edition?: Edition | null): string[] {
  const editionTerms = getEditionSearchTerms(edition);
  const queries: string[] = [];

  // If we have a TCGPlayer alias for this set, try that first
  const alias = tcgplayerSetMap[setName];
  if (alias && alias !== setName) {
    queries.push(`pokemon ${alias} booster pack${editionTerms}`);
  }

  // Primary query with "pokemon" prefix (like the research script uses)
  queries.push(`pokemon ${setName} booster pack${editionTerms}`);

  // Without "pack" — some products are just listed as "booster"
  queries.push(`pokemon ${setName} booster${editionTerms}`);

  // Reordered — sometimes helps with search relevance
  queries.push(`${setName} pokemon booster pack${editionTerms}`);

  return queries;
}

// Try to find the best match from a set of search results
function findBestCandidate(
  results: TCGPlayerSearchResult[],
  setName: string,
  edition?: Edition | null
): MatchResult | null {
  const candidates = results.filter(
    (r) => isBoosterPack(r.productName) && matchesEdition(r.productName, edition)
  );

  if (candidates.length === 0) return null;

  const scored = candidates
    .map((c) => scoreMatch(c, setName, edition))
    .sort((a, b) => b.confidence - a.confidence);

  return scored[0].confidence >= 0.5 ? scored[0] : null;
}

export async function findPackProduct(
  setName: string,
  edition?: Edition | null
): Promise<FindPackResult | null> {
  // Check hardcoded vintage mapping first
  const key = `${setName}|${edition ?? ''}`;
  const vintageId = VINTAGE_PACK_IDS[key];
  if (vintageId) {
    const details = await getProductDetails(vintageId);
    if (details) {
      // Validate product type for vintage packs too
      if (details.productTypeName && !VALID_PRODUCT_TYPES.includes(details.productTypeName)) {
        // Product type mismatch — skip this vintage mapping
      } else {
        return {
          result: {
            productId: vintageId,
            productName: details.productName,
            marketPrice: details.marketPrice,
            lowestPrice: details.lowestPrice,
            imageUrl: getProductImageUrl(vintageId),
            setName: details.setName,
            productUrlName: details.productUrlName,
          },
          confidence: 1.0, // hardcoded IDs are pre-verified
        };
      }
    }
  }

  // Try multiple search queries, stop as soon as we get a good match
  const queries = buildSearchQueries(setName, edition);
  let bestOverall: MatchResult | null = null;

  for (const query of queries) {
    const results = await searchProducts(query);
    const best = findBestCandidate(results, setName, edition);

    if (best) {
      // Keep track of the best match across all queries
      if (!bestOverall || best.confidence > bestOverall.confidence) {
        bestOverall = best;
      }
      // Stop early if we found a high-confidence match
      if (best.confidence >= 0.7) break;
    }
  }

  if (!bestOverall) return null;

  // Validate product type via details endpoint
  const details = await getProductDetails(bestOverall.product.productId);
  if (details?.productTypeName && !VALID_PRODUCT_TYPES.includes(details.productTypeName)) {
    // Wrong product type — this match is invalid
    return null;
  }

  return { result: bestOverall.product, confidence: bestOverall.confidence };
}
